import socket
import struct

def parsing_ethernet_header(data):
    ethernet_header = struct.unpack("!6c6c2s", data)
    ether_src = convert_address(ethernet_header[0:6])
    ehter_dest = convert_address(ethernet_header[6:12])
    ip_header = "0x"+ethernet_header[12].hex()

    print("====== ethernet header ======")
    print("src_mac_address: ", ether_src)
    print("dest_mac_address: ", ehter_dest)
    print("ip_version", ip_header)

def convert_address(data):
    addr = list()
    for i in data:
        addr.append(i.hex())
    addr = ":".join(addr)
    return addr

recv_socket = socket.socket(socket.AF_PACKET, socket.SOCK_RAW, socket.ntohs(0x800))

def parsing_ip_header(data):
    ip_header = struct.unpack("!", data)
    ip_version = convert_address()
    ip_length = convert_address()
    ip_dif_ser_code = convert_address()
    ip_exp_con_noti = convert_address()
    ip_total_length = convert_address()
    ip_identification = convert_address()
    ip_flags = convert_address()
    ip_res_bit = convert_address()
    ip_not_frag = convert_address()
    ip_fragments = convert_address()
    ip_fragments_off = convert_address()
    ip_Time_to_live = convert_address()
    ip_protocol = convert_address()
    ip_head_check = convert_address()
    ip_src_address = convert_address()
    ip_dst_address = conver_address()
    
    print("====== ip address ======")
    print("ip_version : ", ip_version)
    print("ip_Length : ", ip_length)
    print("differentiated_service_codepoint : ", ip_dif_ser_code)
    print("explicit_congestion_notification : ", ip_exp_con_noti)
    print("total_length : ", ip_total_length)
    print("identification : ", ip_identification)
    print("flags : ", ip_flags)
    print(">>>reserved_bit : ", ip_res_bit)
    print(">>>not_fragment : ", ip_not_frag)
    print(">>>fragments : ", ip_fragments)
    print(">>>fragments_offset : ", id_fragment_off)
    print("Time to live : ", ip_Time_to_live)
    print("protocol : ", ip_protocpl)
    print("header checksum : ",ip_head_check)
    print("source_ip_address : ", ip_src_address)
    print("dest_ip_address : ", ip_dst_address)

def parsing_tcp_header(data):
    tcp_header = struct.unpack("!", data)
    tcp_src_port = convert_address()
    tcp_dec_port = convert_address()
    tcp_seq_num = convert_address()
    tcp_ack_num = convert_address()
    tcp_header_len = convert_address()
    tcp_flags = convert_address()
    tcp_reserved = convert_address()
    tcp_nonce = convert_address()
    tcp_cwr = convert_address()
    tcp_urgent = convert_address()
    tcp_ack = convert_address()
    tcp_push = convert_address()
    tcp_reset = convert_address()
    tcp_syn = convert_address()
    tcp_fin = convert_address()
    tcp_window = convert_address()
    tcp_checksum = convert_address()
    tcp_urgent = convert_address()

    print("src_port : ", tcp_src_port)
    print("dec_port : ", tcp_dec_port)
    print("seq_num : ", tcp_seq_num)
    print("ack_num : ", tcp_ack_num)
    print("header_len : ", tcp_header_len)
    print("flags : ", tcp_flags)
    print(">>>reserved : ", tcp_reserved)
    print(">>>nonce : ", tcp_nonce)
    print(">>>cwr : ", tcp_cwr)
    print(">>>urgent : ", tcp_urgent)
    print(">>>ack : ", tcp_ack)
    print(">>>push : ", tcp_push)
    print(">>>reset : ", tcp_reset)
    print(">>>syn : ", tcp_syn)
    print(">>>fin : ", tcp_fin)
    print("window_size_value : ", tcp_window)
    print("checksum : ", tcp_checksum)
    print("urgent_pointer : ", tcp_urgent)

def parsing_udp_header(data):
    udp_header = struct.unpack("!", data)
    udp_src_port = convert_address()
    udp_dst_port = convert_address()
    udp_leng = convert_address()
    udp_checksum = convert_address()

    print("src_port : ", udp_src_port)
    print("dst_port : ", udp_dst_port)
    print("leng : ", udp_leng)
    print("header checksum : 0x", udp_checksum)
